### ISSUE TITLE
How to generate images with ckpts?

### ISSUE THREAD

**Issue by zeyofu** [ConceptBed/evaluations#1]
Hi, is there any guideline on how to generate images using the checkpoints? Also is it possible to release the checkpoints for https://huggingface.co/spaces/mpatel57/ConceptBed?

**Comment by Maitreyapatel** [comment]
The provided checkpoint files correspond to the classifiers used for calculating the `CCD` metric. 
It would be difficult to prove all checkpoints for the ConceptBed baseline methods as they are over 1TB in size. 

However, the results can be easily reproduced by the following approaches:
1. Textual Inversion -- [https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion](https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion)
2. DreamBooth -- [https://github.com/huggingface/diffusers/tree/main/examples/dreambooth](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth)
3. Custom Diffusion -- [https://github.com/huggingface/diffusers/tree/main/examples/custom_diffusion](https://github.com/huggingface/diffusers/tree/main/examples/custom_diffusion)


That said, we are in the process of releasing the Concept Learning framework used in ConceptBed which encompasses the above-mentioned methods.

**Comment by zeyofu** [comment]
Thanks for your reply! I see, yes it makes sense to train by ourselves. I'm also wondering what's the checkpoint to use to test for composition alignment, in scripts/composition_alignment/test_compositions.sh?

**Comment by Maitreyapatel** [comment]
You do not need to provide the checkpoint for the composition alignment. 
Code is configured to use/download the available checkpoint from HuggingFace Hub.

Checkpoint: [dandelin/vilt-b32-finetuned-vqa](https://huggingface.co/dandelin/vilt-b32-finetuned-vqa)

**Comment by Maitreyapatel** [comment]
Closing the issue. Feel free to re-open if needed.
